### ISSUE TITLE
kluster.py syntax error

### ISSUE THREAD

**Issue by ameirshaa** [CERNatschool/cluster-viewer#1]
in line 475, "print "DEBUG: Looping over pixels in the pixel_map:" there is a sytax error: Missing parentheses in call to print.

**Comment by twhyntie** [comment]
@ameirshaa Ah, this is due to some old. I guess it got missed as I don't run in debug mode anymore! Does it stop the code from running on the CernVM?

**Comment by ameirshaa** [comment]
No, not exactly. This was due to my lack of knowledge of the python versions. This was compiled in python 3.5 but I tried to run it on python 2.7. Therefore the print functions all had syntax errors.

i.e. 

In python 3.5 print is written like so: print (...) 
In python 2.7 print is written: print ...

**Comment by twhyntie** [comment]
@ameirshaa Cool, no problem. The CERN@school code runs in 2.7.x, so we don't need to do anything. I will update the `README.md` and close the issue. Thanks!
